# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customerid', models.IntegerField(blank=True, db_column='CustomerID', primary_key=True, serialize=False)),
                ('companyname', models.CharField(blank=True, db_column='CompanyName', max_length=60, null=True)),
                ('contactname', models.CharField(blank=True, db_column='ContactName', max_length=40, null=True)),
                ('contacttitle', models.CharField(blank=True, db_column='ContactTitle', max_length=60, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=60, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=60, null=True)),
                ('state', models.CharField(blank=True, db_column='State', max_length=2, null=True)),
            ],
            options={
                'db_table': 'Customers',
                'verbose_name_plural': 'Customers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employeeid', models.IntegerField(blank=True, db_column='EmployeeID', primary_key=True, serialize=False)),
                ('lastname', models.CharField(blank=True, db_column='LastName', max_length=20, null=True)),
                ('firstname', models.CharField(blank=True, db_column='FirstName', max_length=20, null=True)),
                ('title', models.CharField(blank=True, db_column='Title', max_length=60, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=40, null=True)),
                ('hiredate', models.CharField(blank=True, db_column='HireDate', max_length=25, null=True)),
            ],
            options={
                'db_table': 'Employees',
                'verbose_name_plural': 'Employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orderdetails',
            fields=[
                ('orderdetailid', models.IntegerField(blank=True, db_column='OrderDetailID', primary_key=True, serialize=False)),
                ('orderid', models.IntegerField(blank=True, db_column='OrderID', null=True)),
                ('productid', models.IntegerField(blank=True, db_column='ProductID', null=True)),
                ('unitprice', models.FloatField(blank=True, db_column='UnitPrice', null=True)),
                ('quantity', models.IntegerField(blank=True, db_column='Quantity', null=True)),
            ],
            options={
                'db_table': 'OrderDetails',
                'verbose_name_plural': 'OrderDetails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderid', models.IntegerField(blank=True, db_column='OrderID', primary_key=True, serialize=False)),
                ('customerid', models.IntegerField(blank=True, db_column='CustomerID', null=True)),
                ('employeeid', models.IntegerField(blank=True, db_column='EmployeeID', null=True)),
                ('orderdate', models.CharField(blank=True, db_column='OrderDate', max_length=25, null=True)),
                ('requireddate', models.CharField(blank=True, db_column='RequiredDate', max_length=25, null=True)),
                ('shippeddate', models.CharField(blank=True, db_column='ShippedDate', max_length=25, null=True)),
                ('shipvia', models.IntegerField(blank=True, db_column='ShipVia', null=True)),
                ('freightcharge', models.FloatField(blank=True, db_column='FreightCharge', null=True)),
            ],
            options={
                'db_table': 'Orders',
                'verbose_name_plural': 'Orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shippers',
            fields=[
                ('shipperid', models.IntegerField(blank=True, db_column='ShipperID', primary_key=True, serialize=False)),
                ('companyname', models.CharField(blank=True, db_column='CompanyName', max_length=60, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=20, null=True)),
            ],
            options={
                'db_table': 'Shippers',
                'verbose_name_plural': 'Shippers',
                'managed': False,
            },
        ),
    ]
